# Helper image to run qwc-config-db migrations
FROM alpine:3.21

ENV PGSERVICEFILE=/tmp/pg_service.conf
ENV PGSERVICE=qwc_configdb
ENV ALEMBIC_VERSION=head
ENV QWC_CONFIG_SCHEMA=qwc_config

RUN apk add --no-cache --update postgresql-client py3-alembic py3-psycopg2

COPY alembic.ini /tmp/alembic.ini
COPY alembic /tmp/alembic
COPY run-migrations.sh /tmp/run-migrations.sh

WORKDIR /tmp
ENTRYPOINT ["/tmp/run-migrations.sh"]
